### PR TITLE
Refactor SakuraPlayer and PlayBar components for improved playback management

### PR DESCRIPTION
**Pull request by Ai-Vonie**
- Replaced PlayCallback with a more structured event queue system in SakuraPlayer.
- Enhanced playback control with new methods for seeking and stopping playback.
- Updated SakuraPlayBar to utilize the new SakuraPlayer structure, improving song loading and playback handling.
- Removed unused progress slider methods and added detailed docstrings for clarity.
- Improved cleanup processes in DemoPlayer and SakuraPlayer to prevent resource leaks.
- Added wait time management methods in SakuraPlayBar for better playback control.
- General code cleanup and organization for maintainability.

### CODE REVIEW

**Comment by Ai-Vonie** [comment]
@yuki-sakura-chan Can you, when you make a close pull request to the `master-branch`, sync it with mine `ai_vonie_pre-branch`?

**Comment by yuki-sakura-chan** [comment]
> @yuki-sakura-chan Can you, when you make a close pull request to the `master-branch`, sync it with mine `ai_vonie_pre-branch`?

@Ai-Vonie Are you asking if I should delete your branch when I close this branch?

**Review by yuki-sakura-chan — APPROVED** [review]

**Comment by yuki-sakura-chan** [comment]
@Ai-Vonie Hello, if you're merging, it's best to use "Rebase and Merge" — that's my preferred method. However, how you proceed is up to you.

**Comment by Ai-Vonie** [comment]
> @Ai-Vonie Are you asking if I should delete your branch when I close this branch?

@yuki-sakura-chan, I mean update `ai_vonie_pre-branch` from `master-branch`, after the moment when you **merge pull request** to `master-branch` and close pull request. Because if not, I'll have to delete it myself, make a new one in web Git, delete the local files and download new (old) branch again. Because of these unnecessary machinations, my old local files with settings will be replaced with new ones without.



> @Ai-Vonie Hello, if you're merging, it's best to use "Rebase and Merge" — that's my preferred method. However, how you proceed is up to you.

I don't do the merge, I just open a pull request. You choose how to merge these commits into the `master-branch`. You can also add a description to merge commit.
Rebase and Merge

**Comment by yuki-sakura-chan** [comment]
@Ai-Vonie When I click merge, it seems there’s no sync button available. You might need to handle the synchronization yourself. You can try using the `git merge master` command.

**Pull request merged**
