### PR TITLE
Add musical instruments to DemoPlayer and their support

### PR DESCRIPTION
**Pull request by Ai-Vonie**
- Added new musical instruments
- Now can select an instrument in the settings
- Attempt to eliminate crackling

Known issues:
- Due to the conversion of the audio file, the amount of RAM used increases
- The **electric guitar** is **called LightGuitar**, and there is **no light guitar** for a donation yet.

Need to install a new library `pip install soundfile` and add its version to `requirements.txt`

### CODE REVIEW

**Comment by Ai-Vonie** [comment]
Audio files for musical instruments taken [here](https://github.com/Specy/genshin-music/tree/main/public/assets/audio)

**Comment by Ai-Vonie** [comment]
The old piano didn't go... Where did you get the audio files for [this piano](https://github.com/yuki-sakura-chan/sky-auto-player/tree/master/resources/Instruments/Piano)?

**Comment by yuki-sakura-chan** [comment]
@Ai-Vonie I prefer not to include sound files within the codebase, as doing so would significantly increase the repository size, which is something I want to avoid. Initially, I had a collection of sound files for a dozen instruments locally, but I only included the piano sound in the repository for demonstration purposes. The intention is not for users to pull all sound files directly from the codebase. Instead, I want users to download the sounds via network requests, keeping them separate from the code.

**Comment by yuki-sakura-chan** [comment]
> The old piano didn't go... Where did you get the audio files for [this piano](https://github.com/yuki-sakura-chan/sky-auto-player/tree/master/resources/Instruments/Piano)?

I used the Android file system to retrieve sound files from Sky Studio and placed them in a directory for testing. To prevent forgetting how to debug the system, I only uploaded the piano sound. As mentioned in my previous comment, I prefer not to include sound or other binary files in the code repository.

**Comment by Ai-Vonie** [comment]
Hmm, kk. Maybe tomorrow I'll see what I can do.
Just this week I did some refactoring, logic improvements and adding some functions in lua code for the old farm bot in mmo.

**Pull request closed without merging**
